In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay, f1_score
import matplotlib.pyplot as plt
import numpy as np
import scipy.sparse
import pandas as pd

In [2]:
# ── Labels ───────────────────────────────────────────────────────────────────
y_train       = np.load('saved_features/y_train.npy')
y_val         = np.load('saved_features/y_val.npy')
y_train_no_sw = np.load('saved_features/y_train_no_sw.npy')
y_val_no_sw   = np.load('saved_features/y_val_no_sw.npy')
y_train_raw   = np.load('saved_features/y_train_raw.npy')
y_val_raw     = np.load('saved_features/y_val_raw.npy')

# ── Raw ──────────────────────────────────────────────────────────────────────
X_train_raw = np.load('saved_features/X_train_raw.npy', allow_pickle=True)
X_val_raw   = np.load('saved_features/X_val_raw.npy', allow_pickle=True)

# ── BoW ──────────────────────────────────────────────────────────────────────
X_train_bow       = scipy.sparse.load_npz('saved_features/X_train_bow.npz')
X_val_bow         = scipy.sparse.load_npz('saved_features/X_val_bow.npz')
X_train_bow_no_sw = scipy.sparse.load_npz('saved_features/X_train_bow_no_sw.npz')
X_val_bow_no_sw   = scipy.sparse.load_npz('saved_features/X_val_bow_no_sw.npz')

# ── TF-IDF ───────────────────────────────────────────────────────────────────
X_train_tfidf       = scipy.sparse.load_npz('saved_features/X_train_tfidf.npz')
X_val_tfidf         = scipy.sparse.load_npz('saved_features/X_val_tfidf.npz')
X_train_tfidf_no_sw = scipy.sparse.load_npz('saved_features/X_train_tfidf_no_sw.npz')
X_val_tfidf_no_sw   = scipy.sparse.load_npz('saved_features/X_val_tfidf_no_sw.npz')

# ── Word2Vec Skip-gram ────────────────────────────────────────────────────────
X_train_w2v       = np.load('saved_features/X_train_w2v.npy')
X_val_w2v         = np.load('saved_features/X_val_w2v.npy')
X_train_w2v_no_sw = np.load('saved_features/X_train_w2v_no_sw.npy')
X_val_w2v_no_sw   = np.load('saved_features/X_val_w2v_no_sw.npy')

# ── Word2Vec CBOW ─────────────────────────────────────────────────────────────
X_train_w2v_cbow       = np.load('saved_features/X_train_w2v_cbow.npy')
X_val_w2v_cbow         = np.load('saved_features/X_val_w2v_cbow.npy')
X_train_w2v_cbow_no_sw = np.load('saved_features/X_train_w2v_cbow_no_sw.npy')
X_val_w2v_cbow_no_sw   = np.load('saved_features/X_val_w2v_cbow_no_sw.npy')

# ── GloVe ─────────────────────────────────────────────────────────────────────
X_train_glove       = np.load('saved_features/X_train_glove.npy')
X_val_glove         = np.load('saved_features/X_val_glove.npy')
X_train_glove_no_sw = np.load('saved_features/X_train_glove_no_sw.npy')
X_val_glove_no_sw   = np.load('saved_features/X_val_glove_no_sw.npy')

# ── FinBERT ───────────────────────────────────────────────────────────────────
X_train_finbert = np.load('saved_features/X_train_finbert.npy')
X_val_finbert   = np.load('saved_features/X_val_finbert.npy')

# ── RoBERTa ───────────────────────────────────────────────────────────────────
X_train_roberta = np.load('saved_features/X_train_roberta.npy')
X_val_roberta   = np.load('saved_features/X_val_roberta.npy')

# ── BERTweet ──────────────────────────────────────────────────────────────────
X_train_bertweet = np.load('saved_features/X_train_bertweet.npy')
X_val_bertweet   = np.load('saved_features/X_val_bertweet.npy')

print(f"Train size: {len(y_train):,} tweets")
print(f"Validation size: {len(y_val):,} tweets")

Train size: 7,634 tweets
Validation size: 1,909 tweets


In [3]:
def train_evaluate_lr(X_train, X_val, y_train, y_val, label, max_iter=1000):
    lr = LogisticRegression(
        multi_class='multinomial',  # 3 classes
        class_weight='balanced',    # lidar com o imbalance
        max_iter=max_iter,
        random_state=42,
        n_jobs=-1
    )
    
    lr.fit(X_train, y_train)
    y_pred = lr.predict(X_val)
    
    print(f"\n{'='*55}")
    print(f"  Logistic Regression — {label}")
    print(f"{'='*55}")
    print(classification_report(y_val, y_pred,
                                target_names=['Bearish', 'Bullish', 'Neutral']))
    
    print('\nConfusion Matrix for Validation Data:')
    print(confusion_matrix(y_val, y_pred))
    
    return lr, y_pred

In [4]:
# BoW e TF-IDF
lr_bow,   _ = train_evaluate_lr(X_train_bow,   X_val_bow,   y_train, y_val, label="BoW")
lr_tfidf, _ = train_evaluate_lr(X_train_tfidf, X_val_tfidf, y_train, y_val, label="TF-IDF")

# Word2Vec e GloVe
lr_w2v,   _ = train_evaluate_lr(X_train_w2v,   X_val_w2v,   y_train, y_val, label="Word2Vec Skip-gram")
lr_cbow,  _ = train_evaluate_lr(X_train_w2v_cbow, X_val_w2v_cbow, y_train, y_val, label="Word2Vec CBOW")
lr_glove, _ = train_evaluate_lr(X_train_glove, X_val_glove, y_train, y_val, label="GloVe-100")

# Transformer embeddings
lr_finbert,  _ = train_evaluate_lr(X_train_finbert,  X_val_finbert,  y_train, y_val, label="FinBERT CLS")
lr_roberta,  _ = train_evaluate_lr(X_train_roberta,  X_val_roberta,  y_train, y_val, label="RoBERTa CLS")
lr_bertweet, _ = train_evaluate_lr(X_train_bertweet, X_val_bertweet, y_train, y_val, label="BERTweet CLS")

/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(



  Logistic Regression — BoW
              precision    recall  f1-score   support

     Bearish       0.62      0.64      0.63       288
     Bullish       0.62      0.68      0.65       385
     Neutral       0.88      0.85      0.86      1236

    accuracy                           0.78      1909
   macro avg       0.71      0.72      0.71      1909
weighted avg       0.79      0.78      0.78      1909


Confusion Matrix for Validation Data:
[[ 185   44   59]
 [  37  260   88]
 [  76  115 1045]]


/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(



  Logistic Regression — TF-IDF
              precision    recall  f1-score   support

     Bearish       0.59      0.65      0.62       288
     Bullish       0.62      0.71      0.66       385
     Neutral       0.89      0.83      0.86      1236

    accuracy                           0.78      1909
   macro avg       0.70      0.73      0.71      1909
weighted avg       0.79      0.78      0.78      1909


Confusion Matrix for Validation Data:
[[ 187   46   55]
 [  42  274   69]
 [  87  123 1026]]


/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:203: RuntimeWarning: divide by zero encountered in matmul
  raw_prediction = X @ weights.T + intercept  # ndarray, likely C-contiguous
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:203: RuntimeWarning: overflow encountered in matmul
  raw_prediction = X @ weights.T + intercept  # ndarray, likely C-contiguous
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:203: RuntimeWarning: invalid value encountered in matmul
  raw_prediction = X @ weights.T + intercept  # ndarray, likely C-contiguous
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_line


  Logistic Regression — Word2Vec Skip-gram
              precision    recall  f1-score   support

     Bearish       0.21      0.29      0.25       288
     Bullish       0.37      0.45      0.40       385
     Neutral       0.76      0.64      0.70      1236

    accuracy                           0.55      1909
   macro avg       0.45      0.46      0.45      1909
weighted avg       0.60      0.55      0.57      1909


Confusion Matrix for Validation Data:
[[ 84  96 108]
 [ 73 172 140]
 [238 203 795]]


/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:203: RuntimeWarning: divide by zero encountered in matmul
  raw_prediction = X @ weights.T + intercept  # ndarray, likely C-contiguous
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:203: RuntimeWarning: overflow encountered in matmul
  raw_prediction = X @ weights.T + intercept  # ndarray, likely C-contiguous
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:203: RuntimeWarning: invalid value encountered in matmul
  raw_prediction = X @ weights.T + intercept  # ndarray, likely C-contiguous
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:336: RuntimeWarning: divide by zero encountered in matmul
  grad[:, :n_features] = grad_pointwise.T @ X + l2_reg_strength * weights
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:336: RuntimeWarning: overflow encountered in matmul
  grad[:, :n_


  Logistic Regression — Word2Vec CBOW
              precision    recall  f1-score   support

     Bearish       0.17      0.19      0.18       288
     Bullish       0.30      0.40      0.34       385
     Neutral       0.71      0.62      0.67      1236

    accuracy                           0.51      1909
   macro avg       0.39      0.40      0.40      1909
weighted avg       0.55      0.51      0.53      1909


Confusion Matrix for Validation Data:
[[ 54  97 137]
 [ 60 154 171]
 [198 268 770]]


/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:203: RuntimeWarning: divide by zero encountered in matmul
  raw_prediction = X @ weights.T + intercept  # ndarray, likely C-contiguous
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:203: RuntimeWarning: overflow encountered in matmul
  raw_prediction = X @ weights.T + intercept  # ndarray, likely C-contiguous
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:203: RuntimeWarning: invalid value encountered in matmul
  raw_prediction = X @ weights.T + intercept  # ndarray, likely C-contiguous
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:336: RuntimeWarning: divide by zero encountered in matmul
  grad[:, :n_features] = grad_pointwise.T @ X + l2_reg_strength * weights
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:336: RuntimeWarning: overflow encountered in matmul
  grad[:, :n_


  Logistic Regression — GloVe-100
              precision    recall  f1-score   support

     Bearish       0.40      0.63      0.49       288
     Bullish       0.46      0.58      0.51       385
     Neutral       0.86      0.67      0.75      1236

    accuracy                           0.65      1909
   macro avg       0.57      0.63      0.58      1909
weighted avg       0.71      0.65      0.66      1909


Confusion Matrix for Validation Data:
[[181  54  53]
 [ 80 223  82]
 [197 210 829]]


/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:203: RuntimeWarning: divide by zero encountered in matmul
  raw_prediction = X @ weights.T + intercept  # ndarray, likely C-contiguous
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:203: RuntimeWarning: overflow encountered in matmul
  raw_prediction = X @ weights.T + intercept  # ndarray, likely C-contiguous
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:203: RuntimeWarning: invalid value encountered in matmul
  raw_prediction = X @ weights.T + intercept  # ndarray, likely C-contiguous
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_line


  Logistic Regression — FinBERT CLS
              precision    recall  f1-score   support

     Bearish       0.56      0.78      0.65       288
     Bullish       0.61      0.72      0.66       385
     Neutral       0.90      0.77      0.83      1236

    accuracy                           0.76      1909
   macro avg       0.69      0.76      0.72      1909
weighted avg       0.79      0.76      0.77      1909


Confusion Matrix for Validation Data:
[[224  28  36]
 [ 40 278  67]
 [133 147 956]]


/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:203: RuntimeWarning: divide by zero encountered in matmul
  raw_prediction = X @ weights.T + intercept  # ndarray, likely C-contiguous
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:203: RuntimeWarning: overflow encountered in matmul
  raw_prediction = X @ weights.T + intercept  # ndarray, likely C-contiguous
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:203: RuntimeWarning: invalid value encountered in matmul
  raw_prediction = X @ weights.T + intercept  # ndarray, likely C-contiguous
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:336: RuntimeWarning: divide by zero encountered in matmul
  grad[:, :n_features] = grad_pointwise.T @ X + l2_reg_strength * weights
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_linear_loss.py:336: RuntimeWarning: overflow encountered in matmul
  grad[:, :n_


  Logistic Regression — RoBERTa CLS
              precision    recall  f1-score   support

     Bearish       0.54      0.77      0.64       288
     Bullish       0.65      0.72      0.68       385
     Neutral       0.91      0.79      0.84      1236

    accuracy                           0.77      1909
   macro avg       0.70      0.76      0.72      1909
weighted avg       0.80      0.77      0.78      1909


Confusion Matrix for Validation Data:
[[223  26  39]
 [ 52 279  54]
 [139 126 971]]

  Logistic Regression — BERTweet CLS
              precision    recall  f1-score   support

     Bearish       0.54      0.75      0.63       288
     Bullish       0.61      0.72      0.66       385
     Neutral       0.91      0.77      0.84      1236

    accuracy                           0.76      1909
   macro avg       0.68      0.75      0.71      1909
weighted avg       0.79      0.76      0.77      1909


Confusion Matrix for Validation Data:
[[216  35  37]
 [ 53 277  55]
 [134 145

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b


In [ ]:
data = {
    'Model': ['RoBERTa CLS', 'FinBERT CLS', 'BERTweet CLS', 'BoW', 'TF-IDF', 'GloVe-100', 'Word2Vec Skip-gram', 'Word2Vec CBOW'],
    'Accuracy': ['77%', '76%', '76%', '78%', '78%', '65%', '55%', '51%'],
    'F1 Macro': [0.72, 0.72, 0.71, 0.71, 0.71, 0.58, 0.45, 0.40],
    'F1 Bearish': [0.64, 0.65, 0.63, 0.63, 0.62, 0.49, 0.25, 0.18],
    'F1 Bullish': [0.68, 0.66, 0.66, 0.65, 0.66, 0.51, 0.40, 0.34],
    'F1 Neutral': [0.84, 0.83, 0.84, 0.86, 0.86, 0.75, 0.70, 0.67]
}

df = pd.DataFrame(data)
df = df.sort_values('F1 Macro', ascending=False)

print("\n" + "-"*90)
print("Performance Comparison of Logistic Regression Models")
print("-"*90)
print(df.to_string(index=False))
print("-"*90)


------------------------------------------------------------------------------------------
Performance Comparison of Logistic Regression Models
------------------------------------------------------------------------------------------
             Model Accuracy  F1 Macro  F1 Bearish  F1 Bullish  F1 Neutral
       RoBERTa CLS      77%      0.72        0.64        0.68        0.84
       FinBERT CLS      76%      0.72        0.65        0.66        0.83
      BERTweet CLS      76%      0.71        0.63        0.66        0.84
               BoW      78%      0.71        0.63        0.65        0.86
            TF-IDF      78%      0.71        0.62        0.66        0.86
         GloVe-100      65%      0.58        0.49        0.51        0.75
Word2Vec Skip-gram      55%      0.45        0.25        0.40        0.70
     Word2Vec CBOW      51%      0.40        0.18        0.34        0.67
------------------------------------------------------------------------------------------
